return {
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "catppuccin",
			defaults = {
				lazy = true,
				keymaps = false,
			},
			checker = {
				enabled = true,
			},
		},
	},
	"windwp/nvim-autopairs",
	"nvim-lualine/lualine.nvim",
	"neomake/neomake",
	"machakann/vim-highlightedyank",
	{ "catppuccin/nvim", as = "catppuccin" },
	"mfussenegger/nvim-dap",
	"mfussenegger/nvim-dap-python",
	"neovim/nvim-lspconfig",
	{ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" },
	"voldikss/vim-floaterm",
	"github/copilot.vim",
	"dart-lang/dart-vim-plugin",
	"nvim-lua/plenary.nvim",
	{ "nvim-telescope/telescope.nvim", branch = "0.1.x" },
	"numToStr/Comment.nvim",
	"nvim-tree/nvim-web-devicons",
	"antoinemadec/FixCursorHold.nvim",
	"nvim-neotest/neotest",
	"nvim-neotest/neotest-python",
	"preservim/nerdtree",
	"akinsho/git-conflict.nvim",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-path",
	"hrsh7th/cmp-cmdline",
	"hrsh7th/nvim-cmp",
	"hrsh7th/cmp-vsnip",
	"hrsh7th/vim-vsnip",
	"mattboehm/vim-unstack",
	"rcarriga/nvim-dap-ui",
	"tpope/vim-dadbod",
	"kristijanhusak/vim-dadbod-ui",
	"kristijanhusak/vim-dadbod-completion",
	"MunifTanjim/nui.nvim",
	"rcarriga/nvim-notify",
	"kmontocam/nvim-conda",
	{
		"folke/trouble.nvim",
		dependencies = { "nvim-tree/nvim-web-devicons" },
		opts = {
			mode = "loclist",
		},
	},
	{
		"folke/neodev.nvim",
		opts = {
			library = {
				plugins = { "nvim-dap-ui" },
				types = true,
			},
		},
	},
	"williamboman/mason.nvim",
}
